name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [dev]
    # paths: ['docs/**', 'src/**', 'package.json']

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Check out code 🛎️
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Build
        run: |
          cd docs
          bun install
          bun run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
